project_name: goreleaser-test

before:
    hooks:
        - go mod download
        - go generate ./...

builds:
    - id: goodevening
      dir: .
      main: cmd/goodevening/main.go
      binary: goodevening
      ldflags:
          - -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X
            main.builtBy=goreleaser
      gcflags:
          - all=-trimpath={{.Env.PWD}}
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - darwin
      goarch:
          - amd64

archives:
    - id: goodevening-archives
      builds:
          - goodevening
      format_overrides:
          - goos: darwin
            format: zip
      wrap_in_directory: true
      files:
          - goodevening*/goodevening

checksum:
    disable: true

snapshot:
    name_template: "{{ .Version }}"

changelog:
    skip: false

nfpms:
    - id: goodevening-deb
      package_name: goodevening
      file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
      builds:
          - goodevening
      replacements:
          linux: ""
          amd64: amd64
      vendor: Pachyderm
      homepage: https://example.com/
      maintainer: noreply@example.com
      description: "This is only a test."
      formats:
          - deb
      bindir: /usr/bin

release:
    name_template: "{{ .Version }}"
    prerelease: auto
    disable: false

brews:
    - name: goodevening@{{.Major}}.{{.Minor}}
      ids:
          - goodevening-archives
      homepage: "https://example.com/"
      description: "This is only a test."
      tap:
          owner: example
          name: homebrew-tap
      url_template: "https://example.com/x/y/releases/download/v{{ .Version }}/{{.ArtifactName }}"
      commit_author:
          name: pachyderm
          email: nitin@pachyderm.com
      test: |
          system "#{bin}/goodevening"
      install: |
          bin.install buildpath/goodevening
      skip_upload: true

dockers:
    - image_templates:
          - "jrockway/goodevening:v{{.Version}}"
      skip_push: true
      dockerfile: Dockerfile
